# Site Settings
title:               Kenny Gruchalla, Ph.D.
tagline:             Research
description:         "I'm primarily interested in developing interactive scientific visualization techniques that provide tools for finding meaning in increasingly large and complex data. My research interests include: scientific visualization, immersive visualization, high-performance scientific computing, GPU computing, topology-based feature extraction, human-computer interaction, and physics-based modeling."
ogdescription:       "Dr. Kenny Gruchalla's research homepage -- advancing scientific visualization, energy visualization, and immersive techniques."
baseurl:            #""
url:                #""
github:
  url:               "https://gruchalla.github.io"
author:
  name:              "Kenny Gruchalla"
  email:             "gruchalla@gmail.com"
  twitter:           "GruchallaKenny"
  github:            "gruchalla"
  orcid:             "0000-0002-8155-1175"
  youtube:           "gruchalla"
  linkedin:          "kennygruchalla"
  researchgate:      "Kenny_Gruchalla"
  bluesky:           "gruchalla.bsky.social"


collections:
- papers
- videos
- press
- web
- calls

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:
